// Generated by gencpp from file begin/AddTwoInts.msg
// DO NOT EDIT!


#ifndef BEGIN_MESSAGE_ADDTWOINTS_H
#define BEGIN_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <begin/AddTwoIntsRequest.h>
#include <begin/AddTwoIntsResponse.h>


namespace begin
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace begin


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::begin::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::begin::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::begin::AddTwoInts > {
  static const char* value()
  {
    return "begin/AddTwoInts";
  }

  static const char* value(const ::begin::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::begin::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::begin::AddTwoInts > 
template<>
struct MD5Sum< ::begin::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::begin::AddTwoInts >::value();
  }
  static const char* value(const ::begin::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::begin::AddTwoIntsRequest> should match 
// service_traits::DataType< ::begin::AddTwoInts > 
template<>
struct DataType< ::begin::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::begin::AddTwoInts >::value();
  }
  static const char* value(const ::begin::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::begin::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::begin::AddTwoInts > 
template<>
struct MD5Sum< ::begin::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::begin::AddTwoInts >::value();
  }
  static const char* value(const ::begin::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::begin::AddTwoIntsResponse> should match 
// service_traits::DataType< ::begin::AddTwoInts > 
template<>
struct DataType< ::begin::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::begin::AddTwoInts >::value();
  }
  static const char* value(const ::begin::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGIN_MESSAGE_ADDTWOINTS_H
