// Generated by gencpp from file course_agv_nav/Plan.msg
// DO NOT EDIT!


#ifndef COURSE_AGV_NAV_MESSAGE_PLAN_H
#define COURSE_AGV_NAV_MESSAGE_PLAN_H

#include <ros/service_traits.h>


#include <course_agv_nav/PlanRequest.h>
#include <course_agv_nav/PlanResponse.h>


namespace course_agv_nav
{

struct Plan
{

typedef PlanRequest Request;
typedef PlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Plan
} // namespace course_agv_nav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::course_agv_nav::Plan > {
  static const char* value()
  {
    return "e27848a10f8e7e4030443887dfea101b";
  }

  static const char* value(const ::course_agv_nav::Plan&) { return value(); }
};

template<>
struct DataType< ::course_agv_nav::Plan > {
  static const char* value()
  {
    return "course_agv_nav/Plan";
  }

  static const char* value(const ::course_agv_nav::Plan&) { return value(); }
};


// service_traits::MD5Sum< ::course_agv_nav::PlanRequest> should match 
// service_traits::MD5Sum< ::course_agv_nav::Plan > 
template<>
struct MD5Sum< ::course_agv_nav::PlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::course_agv_nav::Plan >::value();
  }
  static const char* value(const ::course_agv_nav::PlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::course_agv_nav::PlanRequest> should match 
// service_traits::DataType< ::course_agv_nav::Plan > 
template<>
struct DataType< ::course_agv_nav::PlanRequest>
{
  static const char* value()
  {
    return DataType< ::course_agv_nav::Plan >::value();
  }
  static const char* value(const ::course_agv_nav::PlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::course_agv_nav::PlanResponse> should match 
// service_traits::MD5Sum< ::course_agv_nav::Plan > 
template<>
struct MD5Sum< ::course_agv_nav::PlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::course_agv_nav::Plan >::value();
  }
  static const char* value(const ::course_agv_nav::PlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::course_agv_nav::PlanResponse> should match 
// service_traits::DataType< ::course_agv_nav::Plan > 
template<>
struct DataType< ::course_agv_nav::PlanResponse>
{
  static const char* value()
  {
    return DataType< ::course_agv_nav::Plan >::value();
  }
  static const char* value(const ::course_agv_nav::PlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COURSE_AGV_NAV_MESSAGE_PLAN_H
